/**
 * Noms alternatifs (langue non utilisee dans le champ `nom`) pour permettre
 * de retrouver une carte en cherchant son nom anglais OU francais, quelle
 * que soit la langue d'impression de l'exemplaire (FR/EN/JP) - demande
 * d'Axel du 2026-09-29. Cle = valeur exacte de `nom` telle que stockee dans
 * cards.json, valeur = liste de noms alternatifs a injecter dans la cible
 * de recherche.
 *
 * Couverture volontairement centree sur les familles/archetypes les plus
 * recherches (God cards, Magicien Sombre, Dragon Blanc/Noir Aux Yeux
 * Bleus/Rouges, Heros Elementaire/Neos, Numero, Cyber Dragon, Stardust,
 * Six Samurai, staples...) plutot qu'exhaustive sur les 600 noms distincts
 * du catalogue : a completer au fil de l'eau si une carte precise manque.
 */
export const TRADUCTIONS_NOM: Record<string, string[]> = {
  // --- Dieux Egyptiens ---
  "Dragon Ailé De Ra": ["The Winged Dragon of Ra"],
  "Le Dragon Ailé De Ra": ["The Winged Dragon of Ra"],
  "Le Dragon Ailé De Râ": ["The Winged Dragon of Ra"],
  "Winged Dragon Of Ra": ["Dragon Ailé De Ra"],
  "The Winged Dragon Of Ra": ["Dragon Ailé De Ra"],
  "Slifer Le Dragon Céleste": ["Slifer the Sky Dragon"],
  "Slifer The Sky Dragon": ["Slifer Le Dragon Céleste"],
  "Obelisk Le Tourmenteur": ["Obelisk the Tormentor"],
  "Obelisk The Tormentor": ["Obelisk Le Tourmenteur"],

  // --- Magicien Sombre / Dark Magician ---
  "Magicien Sombre": ["Dark Magician"],
  "Magicien Sombre Du Chaos": ["Dark Magician of Chaos"],
  "Magicien Du Chaos Sombre": ["Magician of Black Chaos"],
  "Magicien Sombre Légendaire": ["Legendary Dark Magician"],
  "Magicien Sombre Le Chevalier De La Magie Du Dragon": ["Dark Magician the Dragon Knight"],
  "Magicienne Des Ténèbres": ["Dark Magician Girl"],
  "Magicienne Des Ténèbres Le Dragon Chevalier": ["Dark Magician Girl the Dragon Knight"],
  "Toon Dark Magician Girl": ["Magicienne Toon Des Ténèbres"],
  // Pas une carte "Dark Magician Girl" elle-meme, mais son artwork la montre
  // en avant-plan - les acheteurs la cherchent quand meme par ce nom, demande
  // d'Axel du 2026-10-10.
  "Dark Magical Curtain": ["Dark Magician Girl", "Magicienne Des Ténèbres"],
  // Nom officiel imprime "Esprit De La T.I.C.C." (ANPR-FR017), mais Axel
  // appelle toujours cette carte "Chacu Challhua" (surnom perso) -
  // ajoute le 2026-10-10 pour qu'il la retrouve avec les deux noms.
  "Esprit De La T.I.C.C.": ["Chacu Challhua"],
  "Magicien De La Foi": ["Magician of Faith"],
  "Apprenti Magicien": ["Skilled Dark Magician"],
  "Sorcier Du Chaos": ["Chaos Sorcerer"],

  // --- Blue-Eyes / Dragon Blanc Aux Yeux Bleus ---
  "Dragon Blanc Aux Yeux Bleus": ["Blue-Eyes White Dragon"],
  "Dragon Blanc Aux Yeux Bleu": ["Blue-Eyes White Dragon"],
  "Legend Of Blue-Eyes White Dragon": ["Légende Du Dragon Blanc Aux Yeux Bleus"],
  "Booster Legend Of Blue-Eyes White Dragon 1ère Édition (PSA 10)": ["Legend of Blue-Eyes White Dragon Booster"],
  "Dragon Ultime Aux Yeux Bleus": ["Blue-Eyes Ultimate Dragon"],
  "Dragon Toon Aux Yeux Bleus": ["Blue-Eyes Toon Dragon"],
  "Blue-Eyes Toon Dragon": ["Dragon Toon Aux Yeux Bleus"],
  "Dragon Jumelé D'Explosion Aux Yeux Bleus": ["Blue-Eyes Twin Burst Dragon"],
  "Dragon Rayonnant Aux Yeux Bleus": ["Blue-Eyes Shining Dragon"],
  "Néo Dragon Ultime Aux Yeux Bleus": ["Neo Blue-Eyes Ultimate Dragon"],
  "Trishula Dragon Of The Ice Barrier": ["Trishula, Dragon De La Barrière De Glace"],
  "Brionac, Dragon De La Barrière De Glace": ["Brionac, Dragon of the Ice Barrier"],

  // --- Red-Eyes / Dragon Noir Aux Yeux Rouges ---
  "Dragon Noir Aux Yeux Rouges": ["Red-Eyes Black Dragon"],
  "Dragon De Métal Flamboyant Aux Yeux Rouges": ["Red-Eyes Flare Metal Dragon"],
  "Soldat Dragon Sombre Aux Yeux Rouges": ["Red-Eyes Dark Dragoon"],

  // --- Chaos Emperor / archi-demons ---
  "Dragon Empereur Du Chaos": ["Chaos Emperor Dragon - Envoy of the End"],
  "Dragon Empereur Du Chaos - Émissaire De L'Achèvement": ["Chaos Emperor Dragon - Envoy of the End"],
  "Dragon Empereur Du Chaos Émissaire De L'Achèvement": ["Chaos Emperor Dragon - Envoy of the End"],
  "Chaos Emperor Dragon - Envoy Of The End": ["Dragon Empereur Du Chaos Émissaire De L'Achèvement"],
  "Archdémon De Gilfer": ["Archfiend of Gilfer"],
  "Archfiend Of Gilfer": ["Archdémon De Gilfer"],
  "Archdémon Du Monde Mental": ["Dark World Archfiend"],
  "Bouillant Dragon Rouge Archdémon Du Brisement": ["Scorching Nova Dragon"],
  "Dragon Rouge Archdémon": ["Red Dragon Archfiend"],
  "Dragon Rouge Archdémon / Mode Assaut": ["Red Dragon Archfiend/Assault Mode"],
  "Dragon Rouge Archdémon Mode Assaut": ["Red Dragon Archfiend/Assault Mode"],
  "Tyran Dragon Rouge Archdémon": ["Tyrant Red Dragon Archfiend"],

  // --- Elemental Hero / Neos ---
  "Brasier Héros Élémentaire": ["Elemental Hero Inferno"],
  "Bubbleman Héros Élémentaire": ["Elemental Hero Bubbleman"],
  "Chaleur Héros Élémentaire": ["Elemental Hero Heat"],
  "Chevalier Néos Héros Élémentaire": ["Elemental Hero Neos Knight"],
  "Cyclone Sauvage Héros Du Mal": ["Evil Hero Wild Cyclone"],
  "Darkbright Héros Élémentaire": ["Elemental Hero Darkbright"],
  "Dauphin Aquatique Néo Spacien": ["Neo-Spacian Aqua Dolphin"],
  "Elemental Hero Flame Wingman": ["Héros Élémentaire Homme-Flamme Ailé"],
  "Elemental Hero Ocean": ["Héros Élémentaire Océan"],
  "Elemental Hero Shininx Phoenix Enforcer": ["Héros Élémentaire Exécuteur Phoenix Brillant"],
  "Exécuteur Phoenix": ["Phoenix Enforcer"],
  "Exécuteur Phoenix Héros Élémentaire": ["Elemental Hero Phoenix Enforcer"],
  "Exécuteur Phoenix Lumineux Héros Élémentaire": ["Elemental Hero Shining Phoenix Enforcer"],
  "Golem Foudroyant Héros Du Mal": ["Evil Hero Lightning Golem"],
  "Homme-Oiseau Lumineux": ["Shining Wingman"],
  "Homme-Oiseau Sauvage Héros Élémentaire": ["Elemental Hero Wild Wingman"],
  "Homme-Oiseau À L'Éclat Lumineux": ["Elemental Hero Shining Flare Wingman"],
  "Lame Malveillante Héros Du Mal": ["Evil Hero Malicious Edge"],
  "Maitre De L'Effroi Héros De La Destiné": ["Destiny Hero - Dogma"],
  "Néos Arc-En-Ciel": ["Rainbow Neos"],
  "Rainbow Neos": ["Néos Arc-En-Ciel"],
  "Néos Aérien Héros Élémentaire": ["Elemental Hero Air Neos"],
  "Néos Chaos Héros Élémentaire": ["Elemental Hero Chaos Neos"],
  "Néos Des Tempêtes": ["Storm Neos"],
  "Néos Des Ténèbres": ["Dark Neos"],
  "Néos Divin Héros Élémentaire": ["Elemental Hero Divine Neos"],
  "Néos Flamboyant Héros Élémentaire": ["Elemental Hero Flare Neos"],
  "Néos Géant Héros Élémentaire": ["Elemental Hero Gran Neos"],
  "Néos Héros Élémentaire": ["Elemental Hero Neos"],
  "Noueux Héros Élémentaire": ["Elemental Hero Knospe"],
  "Prodige Infernal Héros Du Mal": ["Evil Hero Infernal Prodigy"],
  "Scarabée Néo-Spacien": ["Neo-Spacian Dark Panther"],
  "Taupe Géante Néo-Spacien": ["Neo-Spacian Grand Mole"],
  "Zéro Absolu Héros Élementaire": ["Elemental Hero Absolute Zero"],
  "Destiny Hero Plasma": ["Héros De La Destinée Plasma"],

  // --- Numéro / Number ---
  "Numéro 101": ["Number 101"],
  "Numéro 101 Honneur Silencieux Arche": ["Number 101: Silent Honor ARK"],
  "Numéro 104": ["Number 104"],
  "Numéro 106 Main De Géant": ["Number 106: Giant Hand"],
  "Numéro 107 Dragon Tachyon": ["Number 107: Galaxy-Eyes Tachyon Dragon"],
  "Numéro 107 Dragon Tachyon Aux Yeux Galactiques": ["Number 107: Galaxy-Eyes Tachyon Dragon"],
  "Numéro 11": ["Number 11"],
  "Numéro 11 Gros Œil": ["Number 11: Big Eye"],
  "Numéro 17 Dragon Léviathan": ["Number 17: Leviathan Dragon"],
  "Numéro 22": ["Number 22"],
  "Numéro 23 Lancelot": ["Number 23: Lancelot, Dark Knight of the Underworld"],
  "Numéro 27 Cuirassé Cuiranoid": ["Number 27: Dreadnought Colossus"],
  "Numéro 39 Utopia The Envoy Of The Light": ["Numéro 39 : Utopia"],
  "Number 39 Utopia The Envoy Of The Light": ["Numéro 39 : Utopia"],
  "Numéro 50": ["Number 50"],
  "Numéro 52 Diamond Crab King": ["Numéro 52 : Roi Crabe Diamant"],
  "Number 52 Diamond Crab King": ["Numéro 52 : Roi Crabe Diamant"],
  "Numéro 61 Volcasaure": ["Number 61: Volcasaurus"],
  "Numéro 62 : Dragon Photon Primordial Aux Yeux Galactiques": ["Number 62: Galaxy-Eyes Prime Photon Dragon"],
  "Numéro 74 Maître Des Lames": ["Number 74: Master of Blades"],
  "Numéro 92 : Dragon Heart-Earth": ["Number 92: Heart-eartH Dragon"],
  "Numéro 92 Dragon Heart-Earth": ["Number 92: Heart-eartH Dragon"],
  "Numéro 99 : Dragon Utopique": ["Number 99: Utopic Dragon"],
  "Numéro C1 Porte Du Chaos": ["Number C1: Chaos Gate"],
  "Numéro C101 Honneur Silencieux Des Ténèbres": ["Number C101: Silent Honor DARK"],
  "Numéro C104 Mascarade Horreur De L'Ombre": ["Number C104: Umbral Horror Masquerade"],
  "Numéro C107 Neo Dragon Tachyon Aux Yeux Galactiques": ["Number C107: Neo Galaxy-Eyes Tachyon Dragon"],
  "Numéro C32 Requin Drakonien": ["Number C32: Shark Drake"],
  "Numéro C32 Requin Drakonien Veiss": ["Number C32: Shark Drake Veiss"],
  "Numéro F0 Futur Dragon Utopique": ["Number F0: Utopic Future"],

  // --- Cyber Dragon ---
  "Cyber Dragon Barrière": ["Cyber Dragon Sieger"],
  "Cyber Dragon Infini": ["Cyber Dragon Infinity"],
  "Cyber Dragon Laser": ["Cyber Dragon Nova"],
  "Cyber Dragon Ultime": ["Cyber End Dragon"],
  "Cyber Dragon Ultime Corrompu": ["Corrupted Cyber End Dragon"],
  "Dragon Électromécanique": ["Cyber Dragon"],
  "Cyber End Dragon The Decisive Strike Dragon": ["Cyber Dragon Ultime"],
  "Revolution Cyber Dragon": ["Cyber Dragon Revolution"],
  "Cyber Canon D'Invocation": ["Cyber Summon Blaster"],
  "Cyber Ogre 2": ["Cyber Ogre 2"],
  "Cyber Phoenix": ["Cyber Phoenix"],
  "Cyber Trancheuse": ["Cyber Slasher"],
  "Cyberténébreux": ["Cyber Dark"],
  "Dragon Cyberténébreux": ["Cyber Dark Dragon"],
  "Queue Cyberténébreuse": ["Cyber Dark Keel"],

  // --- Stardust / Synchro dragons ---
  "Dragon Poussière D'Étoiles": ["Stardust Dragon"],
  "Dragon Poussières D'Étoiles": ["Stardust Dragon"],
  "Stardust Dragon": ["Dragon Poussière D'Étoiles"],
  "Stardust Dragon Victim Sanctuary": ["Dragon Poussière D'Étoiles Refuge Sacrificiel"],
  "Dragon Synchro De L'Aile De Cristal": ["Crystal Wing Synchro Dragon"],
  "Dragon Xyz De La Rebellion": ["Rebellion Xyz Dragon"],
  "Dragon Xyz De La Rebellion Des Ténèbres": ["Dark Rebellion Xyz Dragon"],
  "Dragon Xyz De La Rébellion Des Ténèbres": ["Dark Rebellion Xyz Dragon"],
  "Shooting Majestic Star Dragon": ["Dragon Majestueux Filant Étoile"],
  "Dragon Des Étoiles Majestueux": ["Majestic Star Dragon"],
  "Dragon Rouge Majestueux": ["Majestic Red Dragon"],

  // --- Six Samurai ---
  "Envoyé Des Six Samurai": ["Legendary Six Samurai - Shi En"],
  "Envoyé Des Six Samurais": ["Legendary Six Samurai - Shi En"],
  "Grand Maître Des Six Samouraïs": ["Great Shogun Shien"],
  "Les Six Samouraïs - Zanji": ["Legendary Six Samurai - Zanji"],
  "Ruse Des Six Samourais": ["The Six Samurai United"],
  "Dojo De Shien": ["Shien's Dojo"],
  "Enishi Chancelier De Shien": ["Enishi, Shien's Chancellor"],

  // --- Naturia / Harpie / autres archetypes ---
  "Barkion Naturia": ["Naturia Barkion"],
  "Landoise Naturia": ["Naturia Landoise"],
  "Naturia Exterio": ["Naturia Exterio"],
  "Genlisea Traptrix": ["Traptrix Genlisea"],
  "Allomérus Traptrix": ["Traptrix Allomerus"],
  "Chef D'Orchestre Harpie": ["Harpie's Pet Dragon"],
  "Médium Harpie": ["Harpie Channeler"],
  "Plume De Harpie": ["Harpie's Feather"],
  "Plumeau De Dame Harpie": ["Harpie's Feather Duster"],
  "Le Plumeau De Dame Harpie": ["Harpie's Feather Duster"],
  "Reine Harpie": ["Harpie Queen"],
  "Bête Fantôme Meca Dracossac": ["Phantom Beast Mecha-Dracossack"],
  "Bête Fantôme Méca Hamstrat": ["Phantom Beast Cross-Rat"],
  "Mega Dracossac": ["Mecha-Dracossack"],
  "Gae Bulg Chevalier Dragunité": ["Gae Bolg the Dragon Knight"],
  "Chevalier Dragunité Trident": ["Trident Dragoon"],

  // --- Yubel ---
  "Yubel Terreur Incarnée": ["Yubel - Terror Incarnate"],
  "Yubel Terror Incarnate": ["Yubel Terreur Incarnée"],
  "Yubel The Ultimate Nightmare": ["Yubel Le Cauchemar Ultime"],

  // --- Exodia ---
  "Exodia L'Interdit": ["Exodia the Forbidden One"],
  "Éxodia L'Interdit": ["Exodia the Forbidden One"],
  "Exodia The Forbidden": ["Exodia L'Interdit"],
  "Jambe Droite De L'Interdit": ["Right Leg of the Forbidden One"],
  "Bras Droit De L'Interdit": ["Right Arm of the Forbidden One"],

  // --- Buster Blader / autres iconiques ---
  "Buster Blader": ["Buster Blader"],
  "Gaia Le Dragon Champion": ["Gaia the Dragon Champion"],
  "Chevalier Maître Des Dragons": ["Master of Dragon Knight"],
  "Draco Equiste Paladin Dragon": ["Dragon Knight Draco-Equiste"],
  "Gearfried": ["Gearfried the Iron Knight"],
  "Berfomet": ["Berfomet"],
  "Marshmallon": ["Marshmallon"],

  // --- Monarques ---
  "Caius, Le Monarque Des Ombres": ["Caius the Shadow Monarch"],
  "Mobius Le Monarque De Glace": ["Mobius the Frost Monarch"],
  "Granmarg Le Monarque Des Roches": ["Granmarr the Rock Monarch"],
  "Neptune Le Tyran": ["Neptune, the Tyrant of the Deep"],

  // --- Trous / cartes pièges & magies staples ---
  "Jarre De Cupidité": ["Pot of Greed"],
  "Force De Miroir": ["Mirror Force"],
  "Hommage Torrentiel": ["Torrential Tribute"],
  "Torrential Tribute": ["Hommage Torrentiel"],
  "Trou Noir": ["Dark Hole"],
  "Changement De Coeur": ["Change of Heart"],
  "Charité Gracieuse": ["Graceful Charity"],
  "Graceful Charity": ["Charité Gracieuse"],
  "Le Livre De La Lune": ["Book of Moon"],
  "Dispositif D'Évacuation Obligatoire": ["Compulsory Evacuation Device"],
  "Jugement Solennel": ["Solemn Judgment"],
  "Solemn Judgment": ["Jugement Solennel"],
  "Contrôle Mental": ["Mind Control"],
  "Contrôle Cérébral": ["Brain Control"],
  "Contrôle Cérabral": ["Brain Control"],
  "Monster Reborn": ["Monstre Réincarné"],
  "Raigeki": ["Raigeki"],
  "Polymérisation": ["Polymerization"],
  "Fusion Miraculeuse": ["Miracle Fusion"],
  "Dé-Fusion": ["De-Fusion"],
  "Sacrifice Inutile": ["Needless Tribute"],
  "Retour Inutile": ["Needless Loop"],
  "L'Exhumation Du Tribut": ["Tribute to the Doomed"],
  "Tribute To The Doomed": ["L'Exhumation Du Tribut"],
  "Choc De Byser": ["Ojama Chaos"],
  "Annule Attaque": ["Waboku"],
  "Cylindre Magique": ["Magic Cylinder"],
  "Magic Cylinder": ["Cylindre Magique"],
  "Ristourne": ["Reasoning"],
  "Réglage": ["Trap of Board Eraser"],
  "Rivalarrivée": ["Rivalry of Warlords"],
  "Ordre Impérial": ["Imperial Order"],
  "Malédiction D'Anubis": ["Curse of Anubis"],
  "Malédiction Du Vampire": ["Curse of Vampire"],
  "Appel De L'Être Hanté": ["Call of the Haunted"],
  "Fissure Dimensionnelle": ["Dimensional Fissure"],
  "Fusion Dimensionnelle": ["Dimension Fusion"],
  "Question": ["Question"],
  "Card Of Sanctity": ["Carte De Sainteté"],
  "Confiscation": ["Confiscation"],
  "Snatch Steal": ["Vol Furtif"],
  "Reload": ["Recharge"],
  "Trap Jammer": ["Brouilleur De Piège"],
  "Rope Of Life": ["Corde De Vie"],
  "Relieve Monster": ["Monstre Soulagé"],
  "Statue Of The Wicked": ["Statue Du Mal"],
  "Interdimensional Matter Transporter": ["Transporteur Interdimensionnel De Matière"],
  "Transporteur Interdimensionnel De Matière": ["Interdimensional Matter Transporter"],
  "Ring Of Destruction": ["Anneau De Destruction"],
  "Metal Raiders": ["Envahisseurs De Métal"],

  // --- Divers monstres connus ---
  "Kuriboh": ["Kuriboh"],
  "Kuriboh Ailé Lv10": ["Winged Kuriboh LV10"],
  "Jinzo": ["Jinzo"],
  "Jinzo Superposé": ["Jinzo - Lord"],
  "Chat Sauveteur": ["Cat's Ear Tribe"],
  "Roi Des Poupées": ["Doll King"],
  "Gorz L'Émissaire Des Ténèbres": ["Gorz the Emissary of Darkness"],
  "Le Créateur": ["The Creator"],
  "Le Créateur Des Ténèbres": ["The Creator Incarnate"],
  "Le Renoncé": ["The Forgiving Maiden"],
  "Le Renoncé Aux Milles Yeux": ["Relinquished"],
  "Uria": ["Uria, Lord of Searing Flames"],
  "Uria Seigneur Des Flammes Aveuglantes": ["Uria, Lord of Searing Flames"],
  "Hamon": ["Hamon, Lord of Striking Thunder"],
  "Hamon Le Seigneur Du Tonnerre Fracassant": ["Hamon, Lord of Striking Thunder"],
  "Hamon Seigneur Du Tonnerre Fracassant": ["Hamon, Lord of Striking Thunder"],
  "Raviel": ["Raviel, Lord of Phantasms"],
  "Raviel Empereur Des Phantasmes": ["Raviel, Lord of Phantasms"],
  "Armityle Le Spectre Du Chaos": ["Armityle the Chaos Phantasm"],
  "Sanctuaire Des Âmes": ["Sanctuary of the Sky"],
  "Le Sanctuaire Céleste": ["Sanctuary of the Sky"],
  "Milles Couteaux": ["Thousand Knives"],

  // --- Pokemon ---
  "Chamallot": ["Numel"],
  "Suicune": ["Suicune"],
  "Mewtwo": ["Mewtwo"],
  "Rayquaza": ["Rayquaza"],
  "Rayquaza Ex": ["Rayquaza ex"],
};
